// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

package org.example.xptuto;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class GetUsersCb {
    public abstract void onSuccess(ArrayList<User> users);

    public abstract void onError(String error);

    private static final class CppProxy extends GetUsersCb
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void onSuccess(ArrayList<User> users)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onSuccess(this.nativeRef, users);
        }
        private native void native_onSuccess(long _nativeRef, ArrayList<User> users);

        @Override
        public void onError(String error)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onError(this.nativeRef, error);
        }
        private native void native_onError(long _nativeRef, String error);
    }
}
