// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

package org.example.xptuto;

public final class HttpResponse {


    /*package*/ final Integer code;

    /*package*/ final String body;

    public HttpResponse(
            Integer code,
            String body) {
        this.code = code;
        this.body = body;
    }

    public Integer getCode() {
        return code;
    }

    public String getBody() {
        return body;
    }

    @Override
    public String toString() {
        return "HttpResponse{" +
                "code=" + code +
                "," + "body=" + body +
        "}";
    }

}
