// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

package org.example.xptuto;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class HttpCallback {
    public abstract void onFailure(String reason);

    public abstract void onResponse(HttpResponse response);

    private static final class CppProxy extends HttpCallback
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void onFailure(String reason)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onFailure(this.nativeRef, reason);
        }
        private native void native_onFailure(long _nativeRef, String reason);

        @Override
        public void onResponse(HttpResponse response)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onResponse(this.nativeRef, response);
        }
        private native void native_onResponse(long _nativeRef, HttpResponse response);
    }
}
