// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

package org.example.xptuto;

public final class HttpResponse {


    /*package*/ final String body;

    /*package*/ final short code;

    public HttpResponse(
            String body,
            short code) {
        this.body = body;
        this.code = code;
    }

    public String getBody() {
        return body;
    }

    public short getCode() {
        return code;
    }

    @Override
    public String toString() {
        return "HttpResponse{" +
                "body=" + body +
                "," + "code=" + code +
        "}";
    }

}
