// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

package org.example.xptuto;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class PlatformThreads {
    public abstract void createThread(String name, ThreadFunc func);

    public abstract void runOnMainThread(ThreadFunc func);

    public abstract boolean isMainThread();

    private static final class CppProxy extends PlatformThreads
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void createThread(String name, ThreadFunc func)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_createThread(this.nativeRef, name, func);
        }
        private native void native_createThread(long _nativeRef, String name, ThreadFunc func);

        @Override
        public void runOnMainThread(ThreadFunc func)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_runOnMainThread(this.nativeRef, func);
        }
        private native void native_runOnMainThread(long _nativeRef, ThreadFunc func);

        @Override
        public boolean isMainThread()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isMainThread(this.nativeRef);
        }
        private native boolean native_isMainThread(long _nativeRef);
    }
}
