// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

package org.example.xptuto;

import java.util.Date;

public final class Repo {


    /*package*/ final int id;

    /*package*/ final String name;

    /*package*/ final String fullName;

    /*package*/ final User owner;

    /*package*/ final boolean priv;

    /*package*/ final String htmlUrl;

    /*package*/ final String descr;

    /*package*/ final Date createdAt;

    /*package*/ final Date updatedAt;

    /*package*/ final Date pushedAt;

    public Repo(
            int id,
            String name,
            String fullName,
            User owner,
            boolean priv,
            String htmlUrl,
            String descr,
            Date createdAt,
            Date updatedAt,
            Date pushedAt) {
        this.id = id;
        this.name = name;
        this.fullName = fullName;
        this.owner = owner;
        this.priv = priv;
        this.htmlUrl = htmlUrl;
        this.descr = descr;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.pushedAt = pushedAt;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getFullName() {
        return fullName;
    }

    public User getOwner() {
        return owner;
    }

    public boolean getPriv() {
        return priv;
    }

    public String getHtmlUrl() {
        return htmlUrl;
    }

    public String getDescr() {
        return descr;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public Date getPushedAt() {
        return pushedAt;
    }

    @Override
    public String toString() {
        return "Repo{" +
                "id=" + id +
                "," + "name=" + name +
                "," + "fullName=" + fullName +
                "," + "owner=" + owner +
                "," + "priv=" + priv +
                "," + "htmlUrl=" + htmlUrl +
                "," + "descr=" + descr +
                "," + "createdAt=" + createdAt +
                "," + "updatedAt=" + updatedAt +
                "," + "pushedAt=" + pushedAt +
        "}";
    }

}
